# Generated by Django 4.2.7 on 2023-12-13 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='Topic_name',
            new_name='topic_name',
        ),
    ]
